name: Build documentation for REDA

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 1,4'

jobs:
  build_documentation:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt -y update && sudo apt install virtualenvwrapper gmsh tree texlive texlive-latex-extra cm-super-minimal

    - name: Install CRTomo
      run: |
          wget https://github.com/geophysics-ubonn/titatest/releases/download/vtest2/crtomomod_1.8.0_amd64.deb
          pwd
          sudo dpkg -i crtomomod_1.8.0_amd64.deb

    - name: Create virtualenv
      run: bash ./recreate_venv.sh

    - name: Build the documentation
      run: bash ./build_documentation_ci.sh

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload the html page
        path: 'doc/_build/html/'
